# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import sys


class Ui_JarvisGui(object):
    def setupUi(self, JarvisGui):
        JarvisGui.setObjectName("JarvisGui")
        JarvisGui.resize(1311, 910)
        self.centralwidget = QtWidgets.QWidget(JarvisGui)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(-90, 0, 1411, 911))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setText("")
        self.label_1.setPixmap(QtGui.QPixmap("7LP8.gif"))
        self.label_1.setScaledContents(True)
        self.label_1.setObjectName("label_1")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1120, 840, 71, 31))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"background-color: rgb(0, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1200, 840, 71, 31))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 391, 141))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Jarvis_Loading_Screen.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(900, 40, 331, 71))
        self.textBrowser_2.setAutoFillBackground(False)
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;"
"\n"
"")
        self.textBrowser_2.setOverwriteMode(False)
        self.textBrowser_2.setOpenExternalLinks(True)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(560, 40, 331, 71))
        self.textBrowser_3.setAutoFillBackground(False)
        self.textBrowser_3.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;"
"\n"
"")
        self.textBrowser_3.setOpenExternalLinks(True)
        self.textBrowser_3.setObjectName("textBrowser_3")
        JarvisGui.setCentralWidget(self.centralwidget)

        self.retranslateUi(JarvisGui)
        QtCore.QMetaObject.connectSlotsByName(JarvisGui)


        # Get the absolute path to the current script's directory
        script_dir = os.path.dirname(os.path.abspath(__file__))

        # Construct the absolute paths to the images (assuming they're in the same directory as the script)
        background_image_path = os.path.join(script_dir, "7LP8.gif") 
        loading_image_path = os.path.join(script_dir, "Jarvis_Loading_Screen.gif")

        # Set the images using the absolute paths
        self.label_1.setPixmap(QtGui.QPixmap(background_image_path))
        self.label_2.setPixmap(QtGui.QPixmap(loading_image_path))


    def retranslateUi(self, JarvisGui):
        _translate = QtCore.QCoreApplication.translate
        JarvisGui.setWindowTitle(_translate("JarvisGui", "MainWindow"))
        self.pushButton.setText(_translate("JarvisGui", "Run"))
        self.pushButton_2.setText(_translate("JarvisGui", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisGui = QtWidgets.QMainWindow()
    ui = Ui_JarvisGui()
    ui.setupUi(JarvisGui)
    JarvisGui.show()
    sys.exit(app.exec_())
