# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from pathlib import Path
import sys

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.resize(1308, 807)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 50, 981, 681))
        self.label.setStyleSheet("background-color: transparent;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1170, 680, 111, 101))
        self.pushButton.setStyleSheet("background-color: transparent;")  # Removed border-image
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        # Get the absolute path to the current script's directory
        script_dir = os.path.dirname(os.path.abspath(__file__))

        # Construct the absolute paths to the images
        background_image_path = os.path.join(script_dir, "LCPT.gif")
        button_image_path = os.path.join(script_dir, "pngegg.png")

        # Set the images using the absolute paths and error handling
        try:
            self.label.setMovie(QtGui.QMovie(background_image_path))
            self.label.setScaledContents(True)
            self.label.movie().start()
        except Exception as e:
            print(f"Error loading background image: {e}")

        try:
            icon = QtGui.QIcon(button_image_path)  # Now button_image_path is defined
            self.pushButton.setIcon(icon)
            self.pushButton.setIcon(QtGui.QIcon(button_image_path))
            self.pushButton.setIconSize(self.pushButton.size())
        except Exception as e:
            print(f"Error loading button image: {e}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())