# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisGUI(object):
    def setupUi(self, JarvisGUI):
        JarvisGUI.setObjectName("JarvisGUI")
        JarvisGUI.resize(1311, 925)
        JarvisGUI.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label = QtWidgets.QLabel(JarvisGUI)
        self.label.setGeometry(QtCore.QRect(400, 0, 501, 491))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/AsusVivobook15/Desktop/Python/Jarvis -The AI Assistant/jarvisGui/JarvisUiFiles/Mr3W.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.loadingLabel = QtWidgets.QLabel(JarvisGUI)
        self.loadingLabel.setGeometry(QtCore.QRect(390, 500, 521, 201))
        self.loadingLabel.setText("")
        self.loadingLabel.setPixmap(QtGui.QPixmap("C:/Users/AsusVivobook15/Desktop/Python/Jarvis -The AI Assistant/jarvisGui/JarvisUiFiles/loadingui.gif"))
        self.loadingLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loadingLabel.setObjectName("loadingLabel")
        self.loadingLabel_2 = QtWidgets.QLabel(JarvisGUI)
        self.loadingLabel_2.setGeometry(QtCore.QRect(170, 500, 971, 201))
        self.loadingLabel_2.setText("")
        self.loadingLabel_2.setPixmap(QtGui.QPixmap("C:/Users/AsusVivobook15/Desktop/Python/Jarvis -The AI Assistant/jarvisGui/JarvisUiFiles/9d87081f5ed6b386126871dc70286a50.gif"))
        self.loadingLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.loadingLabel_2.setObjectName("loadingLabel_2")
        self.frame = QtWidgets.QFrame(JarvisGUI)
        self.frame.setGeometry(QtCore.QRect(10, 720, 1241, 191))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.terminalText = QtWidgets.QPlainTextEdit(self.frame)
        self.terminalText.setGeometry(QtCore.QRect(0, 40, 1241, 151))
        self.terminalText.setReadOnly(True)
        self.terminalText.setStyleSheet("background-color: rgb(0,0,0);\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-width:2px;\n"
"border-style:solid;\n"
"font:8pt \"Tahoma\";")
        self.terminalText.setObjectName("plainTextEdit")
        self.textEdit = QtWidgets.QTextEdit(JarvisGUI)
        self.textEdit.setGeometry(QtCore.QRect(10, 720, 1241, 41))
        self.textEdit.setReadOnly(True)
        self.textEdit.setStyleSheet("border-width:2px;\n"
"border-style:solid;\n"
"border-color: rgb(255, 255, 255);\n"
"")
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(JarvisGUI)
        QtCore.QMetaObject.connectSlotsByName(JarvisGUI)

    def retranslateUi(self, JarvisGUI):
        _translate = QtCore.QCoreApplication.translate
        JarvisGUI.setWindowTitle(_translate("JarvisGUI", "JarvisGUI"))
        self.textEdit.setHtml(_translate("JarvisGUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#ffffff;\">TERMINAL</span></p></body></html>"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisGUI = QtWidgets.QWidget()
    ui = Ui_JarvisGUI()
    ui.setupUi(JarvisGUI)
    JarvisGUI.show()
    sys.exit(app.exec_())
